name: 'Hello World!'
description: 'Saying hello to the world!'
author: 'Cătălin George Feștilă <catafest@yahoo.com>'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: catafest-work/ThreeJSTutorial@master

